export const TASK_LIST_REQUEST = "TASK_LIST_REQUEST"
export const TASK_LIST_SUCCESS = "TASK_LIST_SUCCESS"
export const TASK_LIST_FAILED = "TASK_LIST_FAILED"
export const TASK_LIST_RESET = "TASK_LIST_RESET"

export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST"
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS"
export const TASK_CREATE_FAILED = "TASK_CREATE_FAILED"

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST"
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
export const TASK_DELETE_FAILED = "TASK_DELETE_FAILED"